export const doctors = [
	{
		id: 1,
		name: 'Dr. David Gilmour',
		experience: `${Math.floor(Math.random() * 15) + 3} years`,
		clinic: 'PPFN Clinic, Aba',
		rating: 4,
		prospect: 'Gynacology',
		gender: 'Male',
		online: false,
		picture: 'https://randomuser.me/api/portraits/men/85.jpg',
	},
	{
		id: 2,
		name: 'Dr. Mary Shepherd',
		experience: `${Math.floor(Math.random() * 15) + 3} years`,
		clinic: 'PPFN Clinic, Awka',
		rating: 4,
		prospect: 'Ophthalmology',
		gender: 'Female',
		online: true,
		picture: 'https://randomuser.me/api/portraits/women/85.jpg',
	},
	{
		id: 3,
		name: 'Dr. Juan Solo',
		experience: `${Math.floor(Math.random() * 15) + 3} years`,
		clinic: 'Ophtamology',
		rating: 5,
		prospect: 'Gynacology',
		gender: 'Female',
		online: false,
		picture: 'https://randomuser.me/api/portraits/women/95.jpg',
	},
	{
		id: 4,
		name: 'Dr. Chris Alva',
		experience: `${Math.floor(Math.random() * 15) + 3} years`,
		clinic: 'PPFN Clinic, Aba',
		rating: 3,
		prospect: 'Gynaecology',
		gender: 'Male',
		online: true,
		picture: 'https://randomuser.me/api/portraits/men/80.jpg',
	},
	{
		id: 5,
		name: 'Dr. Monique Pier',
		experience: `${Math.floor(Math.random() * 15) + 3} years`,
		clinic: 'PPFN Clinic, Paris',
		rating: 2,
		prospect: 'Diatetics',
		gender: 'Female',
		online: false,
		picture: 'https://randomuser.me/api/portraits/women/99.jpg',
	},
];
export const schedulableTime = [
	'08:00 - 08:30',
	'09:00 - 09:30',
	'10:00 - 10:30',
	'11:00 - 11:30',
	'12:00 - 12:30',
	'13:00 - 13:30',
	'14:00 - 14:30',
];
export const reports2 = [
	{
		id: 1,
		name: "Zianab's Lab Report",
		date: 'July 30, 2022',
		status: 'Opened',
		rating: 4,
	},
	{
		id: 2,
		name: 'Nurse Clara Lawa',
		date: 'July 20, 2022',
		status: 'Received',
		rating: 4,
	},
	{
		id: 3,
		name: 'Doctor Joan Solo',
		date: 'July 17, 2022',
		status: 'Opened',
		rating: 4,
	},
	{
		id: 4,
		name: 'Blake Bala',
		date: 'May 04, 2022',
		status: 'Received',
		rating: 4,
	},
];
export const reports = [
	{
		id: 1,
		name: 'Dr. David Gilmour',
		date: 'May 10, 2022',
		clinic: 'PPFN Clinic, Aba',
		rating: 4,
	},
	{
		id: 2,
		name: 'Dr. Mary Shepherd',
		date: 'May 10, 2022',
		clinic: 'PPFN Clinic, Awka',
		rating: 4,
	},
	{
		id: 3,
		name: 'Dr. Juan Solo',
		date: '1May 10, 2022',
		clinic: 'Ophtamologist',
		rating: 5,
	},
	{
		id: 4,
		name: 'Dr. Chris Alva',
		date: 'May 10, 2022',
		clinic: 'PPFN Clinic, Aba',
		rating: 3,
	},
	{
		id: 5,
		name: 'Dr. Monique Pier',
		date: 'May 10, 2022',
		clinic: 'PPFN Clinic, Paris',
		rating: 2,
	},
];
export const patients = [
	{
		id: 1,
		name: 'Ambros Clare',
		info: 'May 10, 2022 | F | 34Y',
		clinic: 'PPFN Clinic, Aba',
		rating: 4,
		picture: 'https://randomuser.me/api/portraits/women/99.jpg',
	},
	{
		id: 2,
		name: 'Abibat Belllo',
		info: 'July 30, 2022 | F | 28Y',
		clinic: 'PPFN Clinic, Aba',
		rating: 4,
		picture: 'https://randomuser.me/api/portraits/women/21.jpg',
	},
	{
		id: 3,
		name: 'Jerome Bigo',
		info: 'March 03, 2022 | M | 27Y',
		clinic: 'PPFN Clinic, Aba',
		rating: 4,
		picture: 'https://randomuser.me/api/portraits/men/18.jpg',
	},
	{
		id: 4,
		name: 'Shaine Thinling',
		info: 'May 26, 2022 | F | 22Y',
		clinic: 'PPFN Clinic, Aba',
		rating: 3,
		picture: 'https://randomuser.me/api/portraits/women/31.jpg',
	},
];
export const activeUser = {
	id: 1,
	name: 'Sabrina Samoa',
	dateRegistered: '10th May, 2020.',
	address: 'PPFN Clinic, Aba',
	online: false,
	phoneNumber: '09023830868',
	email: 'sabrinasamoa@email.com',
	picture: 'https://via.placeholder.com/150',
};
