export const services = [
  'HIV Aids Prevention & Treatment',
  'Malaria Prevention & Treatment',
  'Maternal & Child Healthcare',
  'Sexual Reproductive Health Services',
  'Family planning services',
  'Screening & management of STIs',
  'Laboratory investigation',
  'Infertility | subfertility services',
  'HIV voluntary testing and counseling',
  'Safe motherhood',
  'Cervical cancer screening',
  'Pre and Post abortion counseling and care',
  'Pregnancy test',
  'Ante natal and post natal care',
  'Adolescents & youth friendly services',
  'Sexual reproductive health training',
  'Rape crisis management',
  'Drug & substance abuse counseling',
];
